name: voceran
description: Aplikasi pembuat voucher Mikrotik v6 gratis dan simpel.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  routeros: ^2.0.0
  cupertino_icons: ^1.0.2
