name: voceran
description: Aplikasi pembuat voucher Mikrotik v6 gratis dan simpel.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  router_os_client: ^2.0.1
  cupertino_icons: ^1.0.8
