name: Build vArranger Controller APK

# Memicu build secara MANUAL saja dari tab Actions di GitHub
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repositori GitHub
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup SDK Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. Mengunduh package/library dan build ke APK Release langsung di root
      - name: Build APK Release
        run: |
          flutter pub get
          flutter build apk --release

      # 5. Upload file APK hasil build ke GitHub Actions
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: varranger-controller-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 6. Kirim file APK otomatis langsung ke Telegram
      - name: Kirim APK ke Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: build/app/outputs/flutter-apk/app-release.apk
          message: |
            🚀 *Build Sukses!*
            Aplikasi vArranger2 Controller versi terbaru sudah matang terakit. Silakan langsung unduh dan instal di HP lewat Telegram.